### ISSUE TITLE
[QUESTION] Identity of cligpt

### ISSUE THREAD

**Issue by D3vil0p3r** [paij0se/cligpt#4]
Hello!
I'm reading the code and it seems cligpt calls OpenAI server for getting requests and returning a response.

What I don't understand is that it provides different answers with respect to ChatGPT website. For example, if I ask to it:
```
$ cligpt 'Who are you?'

I am an individual with a diverse range of skills and interests, looking to make a positive impact in the world.


$ cligpt 'Are you ChatGPT?'

No, I am not ChatGPT.
```
Instead, from the ChatGPT official website:
```
Me: Who are you?

I am a language model called ChatGPT, developed by OpenAI. My purpose is to understand and respond to text inputs, providing information and generating human-like text. Is there something specific you would like to know or talk about?


Me: Are you ChatGPT?

Yes, I am a language model called ChatGPT. I have been trained to understand and respond to text inputs. Is there something specific you would like to know or talk about?
```
So, I don't understand why cligpt gives different answers and says that it is not ChatGPT.

**Comment by D3vil0p3r** [comment]
The answer is that cligpt is using "davinci" model.

Is it possible to implement an argument on cligpt that list all possible free models we can use, and another argument where we can set one of these models?

**Comment by paij0se** [comment]
You can set the model in the config file.
